#!/bin/bash
set -eux # -x for verbose logging to juju debug-log

hooksdir="$PWD/hooks"

zabbix_src="/tmp/zabbix-src/zabbix-2.0.5"

user=`relation-get user`
password=`relation-get password`
host=`relation-get private-address`
database=`relation-get database`
server_name=`config-get server-name`

if [ -z "$database" ] ; then
  exit 0
fi

mysql_exec="mysql -h${host} -u${user} -p${password} ${database}"

if ${mysql_exec} -e "SELECT 1 FROM maintenances LIMIT 0" ; then
  juju-log -l INFO "zabbix database already setup. skipping schema setup"
else
  juju-log "setup zabbix database"

  juju-log "applying database schema"
  ${mysql_exec} < ${zabbix_src}/database/mysql/schema.sql

  juju-log "applying images schema"
  ${mysql_exec} < ${zabbix_src}/database/mysql/images.sql

  juju-log "applying data schema"
  ${mysql_exec} < ${zabbix_src}/database/mysql/data.sql
fi

${hooksdir}/config-changed

open-port 80/tcp
open-port 10050/tcp
open-port 10051/tcp
open-port 10052/tcp
