#!/bin/bash -eux
juju-log "running start hook"

database=`relation-get database`

if [ -z "$database" ] ; then
  juju-log "database relation not setup skipping service start"
  exit 0
fi

service apache2 start
su zabbix -c /usr/local/sbin/zabbix_server
su zabbix -c /usr/local/sbin/zabbix_java/startup.sh
