#!/bin/bash -x
juju-log "running stop hook"

close-port 80/tcp
close-port 10051/tcp
close-port 10051/udp
close-port 10052/tcp
close-port 10052/udp

service apache2 stop

pkill -9 com.zabbix.gateway.JavaGateway
rm -f /tmp/zabbix_java.pid

pkill -9 zabbix_server

exit 0
